/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package healthreport;

import ValidationClasses.Validation;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Tajmirkhan
 */
public class Add_Test extends javax.swing.JInternalFrame {
    DataBase db;
    String tst_m_id="0",tst_m_name,tst_m_units,tst_m_normalRange,tst_m_price,tst_m_note;
    String tst_id,tst_name,tst_normalRange,tst_price="0",tst_units;
    DefaultTableModel model_main;
    DefaultTableModel model_child;
    /**
     * Creates new form Add_Test
     */
    public Add_Test() {
        initComponents();
        db=new DataBase();
         model_main =(DefaultTableModel)tst_main_table.getModel();
         model_child=(DefaultTableModel)tst_child_table.getModel();
         showDataIntoMainTable();
    } 
       void getDataFromChildTextField(){
           tst_name=tst_child_name_tf.getText();
           tst_units=tst_child_units_tf.getText();
           //tst_price=tst_child_price_tf.getText();
           tst_price="";
           tst_normalRange=tst_child_normalRange_tf.getText();
           
       }  
       void showDataIntoMainTable(){
              model_main.setRowCount(0);
           ResultSet rs=db.retriveDataFromMainTest();
        //dr_table.setModel(DbUtils.resultSetToTableModel(rs)); 
    try {    
        while(rs.next()){
            model_main.addRow(new Object[]{rs.getInt(Utilities.TST_ID),rs.getString(Utilities.TST_NAME),rs.getString(Utilities.TST_UNITS)
               ,rs.getString(Utilities.TST_NORMALRANGE),rs.getString(Utilities.TST_PRICE)});
        }
//        dr_table.setRowSelectionAllowed(true);
        tst_main_table.getTableHeader().setReorderingAllowed(true);
    } catch (Exception ex) {
        System.out.println(ex.toString());
    }
     }
    void getDataFromTexField(){
          tst_m_name=tst_name_tf.getText();
          tst_m_units=tst_units_tf.getText();
          tst_m_normalRange=tst_normalRange_tf.getText();
          tst_m_price=tst_price_tf.getText();
          tst_m_note=tst_note_tf1.getText();
      }
    void setEmptyTextField(){
         tst_name_tf.setText("");
         tst_units_tf.setText("");
         tst_normalRange_tf.setText("");
         tst_price_tf.setText("");
         tst_note_tf1.setText("");
         test_main_name_lb.setText("");
    }
     void setEmptyDataInChildTextField(){
          tst_id="";
          tst_child_name_tf.setText("");
          tst_child_units_tf.setText("");
          tst_child_normalRange_tf.setText("");
          tst_child_price_tf.setText("");
      }
     private void filterTable(String query){
         TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model_main);
         tst_main_table.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)"+query));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tst_search_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tst_main_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tst_name_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tst_normalRange_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tst_price_tf = new javax.swing.JTextField();
        tst_delete_btn = new javax.swing.JButton();
        tst_save_btn = new javax.swing.JButton();
        tst_update_btn = new javax.swing.JButton();
        tst_units_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tst_note_tf1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tst_child_search_tf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tst_child_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tst_child_name_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tst_child_normalRange_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tst_child_price_tf = new javax.swing.JTextField();
        tst_child_update_btn = new javax.swing.JButton();
        tst_child_save_btn = new javax.swing.JButton();
        tst_child_delete_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tst_child_units_tf = new javax.swing.JTextField();
        test_main_name_lb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(173, 31, 31));
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(900, 600));

        jPanel2.setBackground(new java.awt.Color(173, 31, 31));

        jPanel4.setBackground(new java.awt.Color(173, 31, 31));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Test Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(173, 31, 31));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tst_search_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_search_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_search_tf.setForeground(new java.awt.Color(255, 255, 255));
        tst_search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_search_tfActionPerformed(evt);
            }
        });
        tst_search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tst_search_tfKeyReleased(evt);
            }
        });

        tst_main_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Units", "Normal Range", "Price"
            }
        ));
        tst_main_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tst_main_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tst_main_table);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(51, 51, 51)
                        .addComponent(tst_search_tf))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tst_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(173, 31, 31));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Main Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        tst_name_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_name_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_name_tf.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Normal Range");

        tst_normalRange_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_normalRange_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_normalRange_tf.setForeground(new java.awt.Color(255, 255, 255));
        tst_normalRange_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_normalRange_tfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        tst_price_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_price_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_price_tf.setForeground(new java.awt.Color(255, 255, 255));
        tst_price_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_price_tfActionPerformed(evt);
            }
        });
        tst_price_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tst_price_tfKeyPressed(evt);
            }
        });

        tst_delete_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_delete_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_delete_btn.setText("Delete");
        tst_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_delete_btnActionPerformed(evt);
            }
        });

        tst_save_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_save_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_save_btn.setText("Save");
        tst_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_save_btnActionPerformed(evt);
            }
        });

        tst_update_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_update_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_update_btn.setText("Update");
        tst_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_update_btnActionPerformed(evt);
            }
        });

        tst_units_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_units_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_units_tf.setForeground(new java.awt.Color(255, 255, 255));
        tst_units_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_units_tfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Units");

        tst_note_tf1.setBackground(new java.awt.Color(109, 12, 12));
        tst_note_tf1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_note_tf1.setForeground(new java.awt.Color(255, 255, 255));
        tst_note_tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_note_tf1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Note:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(tst_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tst_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tst_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tst_note_tf1)
                            .addComponent(tst_units_tf)
                            .addComponent(tst_price_tf)
                            .addComponent(tst_name_tf)
                            .addComponent(tst_normalRange_tf))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tst_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tst_units_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tst_normalRange_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tst_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tst_note_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tst_delete_btn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tst_update_btn)
                            .addComponent(tst_save_btn))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(173, 31, 31));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Child Test Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(173, 31, 31));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tst_child_search_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_child_search_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_search_tf.setForeground(new java.awt.Color(255, 255, 255));
        tst_child_search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_child_search_tfActionPerformed(evt);
            }
        });
        tst_child_search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tst_child_search_tfKeyReleased(evt);
            }
        });

        tst_child_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Units", "Normal Range", "Price", "MainTest"
            }
        ));
        tst_child_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tst_child_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tst_child_table);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(53, 53, 53)
                        .addComponent(tst_child_search_tf))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(tst_child_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(173, 31, 31));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Child Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        tst_child_name_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_child_name_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_name_tf.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Normal Range");

        tst_child_normalRange_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_child_normalRange_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_normalRange_tf.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");

        tst_child_price_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_child_price_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_price_tf.setForeground(new java.awt.Color(255, 255, 255));

        tst_child_update_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_update_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_child_update_btn.setText("Update");
        tst_child_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_child_update_btnActionPerformed(evt);
            }
        });

        tst_child_save_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_save_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_child_save_btn.setText("Save");
        tst_child_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_child_save_btnActionPerformed(evt);
            }
        });

        tst_child_delete_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_delete_btn.setForeground(new java.awt.Color(109, 12, 12));
        tst_child_delete_btn.setText("Delete");
        tst_child_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tst_child_delete_btnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Units");

        tst_child_units_tf.setBackground(new java.awt.Color(109, 12, 12));
        tst_child_units_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tst_child_units_tf.setForeground(new java.awt.Color(255, 255, 255));

        test_main_name_lb.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        test_main_name_lb.setForeground(new java.awt.Color(255, 255, 255));
        test_main_name_lb.setText("jLabel11");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(tst_child_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tst_child_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tst_child_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tst_child_units_tf)
                            .addComponent(tst_child_price_tf)
                            .addComponent(tst_child_name_tf)
                            .addComponent(tst_child_normalRange_tf)
                            .addComponent(test_main_name_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(test_main_name_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tst_child_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tst_child_units_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tst_child_normalRange_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tst_child_price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tst_child_delete_btn)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tst_child_update_btn)
                            .addComponent(tst_child_save_btn)))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tst_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_delete_btnActionPerformed
          getDataFromTexField();
         db.deleteFromMainTestData(tst_m_id);       
         setEmptyTextField();
         showDataIntoMainTable();
    }//GEN-LAST:event_tst_delete_btnActionPerformed

    private void tst_search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_search_tfActionPerformed

    private void tst_search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tst_search_tfKeyReleased
       filterTable(tst_search_tf.getText().toLowerCase());
       
    }//GEN-LAST:event_tst_search_tfKeyReleased

    private void tst_child_search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_child_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_child_search_tfActionPerformed

    private void tst_child_search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tst_child_search_tfKeyReleased
       filterChildTable(tst_child_search_tf.getText().toLowerCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_child_search_tfKeyReleased

    private void tst_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_save_btnActionPerformed
         getDataFromTexField();
        if(!tst_m_name.equals("")){
            db.insertIntoMainTestTable(tst_m_name,tst_m_units,tst_m_price,tst_m_normalRange,tst_m_note);
            setEmptyTextField();
            showDataIntoMainTable();

        }else
        {
            JOptionPane.showMessageDialog(null,"Pleas Eneter Test Name");
        }
    }//GEN-LAST:event_tst_save_btnActionPerformed

    private void tst_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_update_btnActionPerformed
        getDataFromTexField();
        db.updateMainTestTable(tst_m_id,tst_m_name,tst_m_units,tst_m_price,tst_m_normalRange);// TODO add your handling code here:
        showDataIntoMainTable();
        setEmptyTextField();
    }//GEN-LAST:event_tst_update_btnActionPerformed

    private void tst_child_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_child_update_btnActionPerformed
        getDataFromChildTextField();
        db.updateChildTestTable(tst_id,tst_name,tst_units,tst_price,tst_normalRange);           
        setEmptyDataInChildTextField();
        showDataIntoChildWithTheHelpOfMainTable(tst_m_id);
    }//GEN-LAST:event_tst_child_update_btnActionPerformed

    private void tst_child_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_child_save_btnActionPerformed
        // TODO add your handling code here:
        
        getDataFromChildTextField();
        if(tst_m_id.equals("0")){
            JOptionPane.showMessageDialog(null,"select any item in the main table");
        }
       else{
        db.insertIntoChildTable(tst_name,tst_units,tst_price,tst_normalRange,tst_m_id);
        setEmptyDataInChildTextField();
        showDataIntoChildWithTheHelpOfMainTable(tst_m_id);
        }
    }//GEN-LAST:event_tst_child_save_btnActionPerformed

    private void tst_child_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_child_delete_btnActionPerformed
       getDataFromChildTextField();
        db.deleteFromChildTable(tst_id);        // TODO add your handling code here:
        setEmptyDataInChildTextField();
        showDataIntoChildWithTheHelpOfMainTable(tst_m_id);
    }//GEN-LAST:event_tst_child_delete_btnActionPerformed
        
  void showDataIntoChildWithTheHelpOfMainTable(String tst_id){
          model_child.setRowCount(0);
           ResultSet rs=db.retriveDataFromChildTestWithTheHelpOfMainTable(tst_id);
        //dr_table.setModel(DbUtils.resultSetToTableModel(rs)); 
           System.out.println("call");
    try {    
        while(rs.next()){
                       System.out.println("call");

           System.out.print(rs.getString(Utilities.TDET_ID));
            
            model_child.addRow(new Object[]{rs.getInt(Utilities.TDET_ID),rs.getString(Utilities.TDET_NAME),rs.getString(Utilities.TDET_UNITS)
               ,rs.getString(Utilities.TDET_NORMALRANGE),rs.getString(Utilities.TDET_PRICE),rs.getString(Utilities.TST_NAME)});
        }
//        dr_table.setRowSelectionAllowed(true);
        tst_child_table.getTableHeader().setReorderingAllowed(true);
    } catch (Exception ex) {
        System.out.println(ex.toString());
    }
    
    }
    
    private void tst_main_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tst_main_tableMouseClicked
        
        setEmptyDataInChildTextField(); 
        
        int i=tst_main_table.getSelectedRow();
               
        tst_m_id=tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),0).toString();
        test_main_name_lb.setText(tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),1).toString());
        tst_name_tf.setText(tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),1).toString());
        tst_units_tf.setText(tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),2).toString());
        tst_price_tf.setText(tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),3).toString());
        tst_normalRange_tf.setText(tst_main_table.getModel().getValueAt(tst_main_table.convertRowIndexToModel(i),4).toString());
        
        getDataFromTexField();
        showDataIntoChildWithTheHelpOfMainTable(tst_m_id); // show data in child table 
    }//GEN-LAST:event_tst_main_tableMouseClicked

    private void tst_normalRange_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_normalRange_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_normalRange_tfActionPerformed

    private void tst_units_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_units_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_units_tfActionPerformed

    private void tst_price_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_price_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_price_tfActionPerformed
      void filterChildTable(String query){
          TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model_child);
         tst_child_table.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)"+query));
      }
    private void tst_child_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tst_child_tableMouseClicked
        // TODO add your handling code here:
         int i=tst_child_table.getSelectedRow();
               
        tst_id=tst_child_table.getModel().getValueAt(tst_child_table.convertRowIndexToModel(i),0).toString();
        tst_child_name_tf.setText(tst_child_table.getModel().getValueAt(tst_child_table.convertRowIndexToModel(i),1).toString());
        tst_child_units_tf.setText(tst_child_table.getModel().getValueAt(tst_child_table.convertRowIndexToModel(i),2).toString());
        tst_child_normalRange_tf.setText(tst_child_table.getModel().getValueAt(tst_child_table.convertRowIndexToModel(i),3).toString());
        tst_child_price_tf.setText(tst_child_table.getModel().getValueAt(tst_child_table.convertRowIndexToModel(i),4).toString());
        getDataFromTexField();
    }//GEN-LAST:event_tst_child_tableMouseClicked

    private void tst_note_tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tst_note_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tst_note_tf1ActionPerformed

    private void tst_price_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tst_price_tfKeyPressed
      Validation.validateInt(tst_price_tf);        // TODO add your handling code here:
    }//GEN-LAST:event_tst_price_tfKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel test_main_name_lb;
    private javax.swing.JButton tst_child_delete_btn;
    private javax.swing.JTextField tst_child_name_tf;
    private javax.swing.JTextField tst_child_normalRange_tf;
    private javax.swing.JTextField tst_child_price_tf;
    private javax.swing.JButton tst_child_save_btn;
    private javax.swing.JTextField tst_child_search_tf;
    private javax.swing.JTable tst_child_table;
    private javax.swing.JTextField tst_child_units_tf;
    private javax.swing.JButton tst_child_update_btn;
    private javax.swing.JButton tst_delete_btn;
    private javax.swing.JTable tst_main_table;
    private javax.swing.JTextField tst_name_tf;
    private javax.swing.JTextField tst_normalRange_tf;
    private javax.swing.JTextField tst_note_tf1;
    private javax.swing.JTextField tst_price_tf;
    private javax.swing.JButton tst_save_btn;
    private javax.swing.JTextField tst_search_tf;
    private javax.swing.JTextField tst_units_tf;
    private javax.swing.JButton tst_update_btn;
    // End of variables declaration//GEN-END:variables
}
