/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package healthreport;

import Toast.AndroidLikeToast;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JFrame;


/**
 *
 * @author Tajmirkhan
 */

public class Add_Dr extends javax.swing.JInternalFrame {
DataBase db;
DefaultTableModel model;
String dr_id,dr_name,dr_phone,dr_address,dr_spaciliazation,dr_gender;
    /**
     * Creates new form Add_Dr
     */
    public Add_Dr() {
        initComponents();
         db=new DataBase();
         buttonGroup2.add(male_rbtn);
         buttonGroup2.add(female_rbtn);
         model =(DefaultTableModel)dr_table.getModel();
         showDataIntoDoctorTable();       
    }
    
     private void showDataIntoDoctorTable(){
           model.setRowCount(0);
           ResultSet rs=db.reteriveDataFromDoctor();
        //dr_table.setModel(DbUtils.resultSetToTableModel(rs));
         
    try {    
        while(rs.next()){
            model.addRow(new Object[]{rs.getInt(Utilities.DR_ID),rs.getString(Utilities.DR_NAME),
                rs.getString(Utilities.DR_GENDER),rs.getString(Utilities.DR_PHONE),
                rs.getString(Utilities.DR_SPECIALIZATION),rs.getString(Utilities.DR_ADDRESS)});
        }
//        dr_table.setRowSelectionAllowed(true);
        dr_table.getTableHeader().setReorderingAllowed(true);
    } catch (Exception ex) {
        System.out.println(ex.toString());
    }
          }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dr_phone_tf = new javax.swing.JTextField();
        dr_name_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dr_specialization_tf = new javax.swing.JTextField();
        add_dr_save_btn = new javax.swing.JButton();
        female_rbtn = new javax.swing.JRadioButton();
        dr_address_ta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add_updatel_bt = new javax.swing.JButton();
        add_delete_btn = new javax.swing.JButton();
        male_rbtn = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        dr_search_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dr_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(173, 31, 31));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(173, 31, 31));

        jPanel2.setBackground(new java.awt.Color(173, 31, 31));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Doctor Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        dr_phone_tf.setBackground(new java.awt.Color(109, 12, 12));
        dr_phone_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dr_phone_tf.setForeground(new java.awt.Color(255, 255, 255));

        dr_name_tf.setBackground(new java.awt.Color(109, 12, 12));
        dr_name_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dr_name_tf.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");

        dr_specialization_tf.setBackground(new java.awt.Color(109, 12, 12));
        dr_specialization_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dr_specialization_tf.setForeground(new java.awt.Color(255, 255, 255));

        add_dr_save_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add_dr_save_btn.setForeground(new java.awt.Color(109, 12, 12));
        add_dr_save_btn.setText("Save");
        add_dr_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_dr_save_btnActionPerformed(evt);
            }
        });

        female_rbtn.setBackground(new java.awt.Color(173, 31, 31));
        female_rbtn.setForeground(new java.awt.Color(255, 255, 255));
        female_rbtn.setText("Female");

        dr_address_ta.setBackground(new java.awt.Color(109, 12, 12));
        dr_address_ta.setColumns(20);
        dr_address_ta.setForeground(new java.awt.Color(255, 255, 255));
        dr_address_ta.setRows(5);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("specialization");

        add_updatel_bt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add_updatel_bt.setForeground(new java.awt.Color(109, 12, 12));
        add_updatel_bt.setText("Update");
        add_updatel_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_updatel_btActionPerformed(evt);
            }
        });

        add_delete_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add_delete_btn.setForeground(new java.awt.Color(109, 12, 12));
        add_delete_btn.setText("Delete");
        add_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_delete_btnActionPerformed(evt);
            }
        });

        male_rbtn.setBackground(new java.awt.Color(173, 31, 31));
        male_rbtn.setForeground(new java.awt.Color(255, 255, 255));
        male_rbtn.setText("Male");
        male_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_rbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dr_specialization_tf)
                                .addComponent(dr_phone_tf)
                                .addComponent(dr_name_tf)
                                .addComponent(dr_address_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(male_rbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female_rbtn))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add_dr_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_updatel_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(add_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dr_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dr_phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dr_specialization_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dr_address_ta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(male_rbtn)
                    .addComponent(female_rbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_dr_save_btn)
                    .addComponent(add_updatel_bt)
                    .addComponent(add_delete_btn))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(173, 31, 31));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Doctor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        dr_search_tf.setBackground(new java.awt.Color(109, 12, 12));
        dr_search_tf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dr_search_tf.setForeground(new java.awt.Color(255, 255, 255));
        dr_search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr_search_tfActionPerformed(evt);
            }
        });
        dr_search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dr_search_tfKeyReleased(evt);
            }
        });

        dr_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "phone", "spacilization", "address"
            }
        ));
        dr_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dr_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dr_table);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)
                        .addComponent(dr_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dr_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 10);
        jPanel5.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void getDataFromTextField(){
        dr_name=dr_name_tf.getText().toLowerCase();
        dr_phone=dr_phone_tf.getText();
        dr_spaciliazation=dr_specialization_tf.getText();
        dr_address=dr_address_ta.getText();
        dr_gender=getGender();
     }
     private void setEmptyDataTextField(){
         dr_name_tf.setText("");
            dr_phone_tf.setText("");
            dr_specialization_tf.setText("");
            dr_address_ta.setText("");
            dr_id="";
            buttonGroup2.clearSelection();
     }
    private void add_dr_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_dr_save_btnActionPerformed
        // TODO add your handling code here:
        getDataFromTextField();
        if(!(dr_name.equals("") || dr_gender.equals(""))){
            db.insertDoctor(dr_name,dr_gender,dr_phone,dr_spaciliazation,dr_address);
            setEmptyDataTextField();
            showDataIntoDoctorTable();
            ToastMessage("Doctore is added");
        }else{
            JOptionPane.showMessageDialog(null,"Pleas name must be enter");
        }
    }//GEN-LAST:event_add_dr_save_btnActionPerformed

    private void ToastMessage(String value){
        final JDialog dialog = new AndroidLikeToast(Add_Dr.this, true, value);
                Timer timer = new Timer(AndroidLikeToast.LENGTH_SHORT, new ActionListener() {
 
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dialog.setVisible(false);
                        dialog.dispose();
                    }
                });
                timer.setRepeats(false);
                timer.start();
 
                dialog.setVisible(true); 
    }
    String getGender()
      {
    if(male_rbtn.isSelected())
    {
        return "Male";
    }
    else if(female_rbtn.isSelected())
    {
        return "Female";
    }
    else
    {
        return "";
    }
}
    private void male_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_rbtnActionPerformed

    private void dr_search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr_search_tfActionPerformed

    private void dr_search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dr_search_tfKeyReleased
       filterTable(dr_search_tf.getText().toLowerCase());
    }//GEN-LAST:event_dr_search_tfKeyReleased

    private void dr_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dr_tableMouseClicked
              // TODO add your handling code here:
        int i=dr_table.getSelectedRow();
        
        dr_id=dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),0).toString();
        dr_name_tf.setText(dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),1).toString());
        String str=dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),2).toString();
        dr_phone_tf.setText(dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),3).toString());
        dr_specialization_tf.setText(dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),4).toString());
        dr_address_ta.setText(dr_table.getModel().getValueAt(dr_table.convertRowIndexToModel(i),5).toString());
        if(str.equalsIgnoreCase("Male")){
            male_rbtn.setSelected(true);
        }else if(str.equalsIgnoreCase("Female")){
            female_rbtn.setSelected(true);
        }
        getDataFromTextField();
    }//GEN-LAST:event_dr_tableMouseClicked

    private void add_updatel_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_updatel_btActionPerformed
        getDataFromTextField();
        db.updateDoctorTable(dr_id,dr_name,dr_gender,dr_phone,dr_spaciliazation,dr_address);        // TODO add your handling code here:
        setEmptyDataTextField();
        showDataIntoDoctorTable();
        ToastMessage("Successfully Updated");
    }//GEN-LAST:event_add_updatel_btActionPerformed

    private void add_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_delete_btnActionPerformed
         getDataFromTextField();
        db.DeleteDoctorFromTable(dr_id);        // TODO add your handling code here:
         setEmptyDataTextField();
         showDataIntoDoctorTable();
                 ToastMessage("Successfully Deleted");
    }//GEN-LAST:event_add_delete_btnActionPerformed
     private void filterTable(String query){
         TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
         dr_table.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)"+query));
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_delete_btn;
    private javax.swing.JButton add_dr_save_btn;
    private javax.swing.JButton add_updatel_bt;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea dr_address_ta;
    private javax.swing.JTextField dr_name_tf;
    private javax.swing.JTextField dr_phone_tf;
    private javax.swing.JTextField dr_search_tf;
    private javax.swing.JTextField dr_specialization_tf;
    private javax.swing.JTable dr_table;
    private javax.swing.JRadioButton female_rbtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male_rbtn;
    // End of variables declaration//GEN-END:variables
}
