/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package healthreport;

import java.awt.GridBagConstraints;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Tajmirkhan
 */
public class splash_scrren extends javax.swing.JFrame {

       int i=0;
    public splash_scrren() {
        initComponents();
        jLabel2.add(jLabel1,CENTER_ALIGNMENT);
          
           
       // setVisible(false);
       // setResizable(true);
       // try {
    //InetAddress ip = InetAddress.getLocalHost();
    //System.out.println("Current IP address : " + ip.getHostAddress());

    //Enumeration<NetworkInterface> networks = NetworkInterface.getNetworkInterfaces();
    //while(networks.hasMoreElements()) {
     // NetworkInterface network = networks.nextElement();
     // byte[] mac = network.getHardwareAddress();
         
     // if(mac != null) {
       // System.out.print("Current MAC address : ");
      
     //   StringBuilder sb = new StringBuilder();
        //for ( i = 0; i < mac.length; i++) {
        //  sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
       // }
        //System.out.println(sb.toString());
        //3C-A9-F4-02-FA-05 kafeel
        //12-16-d8-3E-DD-FA yousaf
        //00-24-D6-9D-F5-04 me
        //28-B2-BD-05-2E-95 almass
        //0C-5B-8F-27-9A-64
        //if(sb.toString().equals("0C-5B-8F-27-9A-64")){
            System.out.println("sameee");
             newth obj=new newth();
             obj.start();
             setLocationRelativeTo(null);
        //}
      //}
      
   // }
   
            //JOptionPane.showMessageDialog(null,"i want to check the mac address");
        
//  } catch (UnknownHostException e) {
//    e.printStackTrace();
//  } catch (SocketException e){
//    e.printStackTrace();
//  }
       
    }
 MainScreen scn=new MainScreen();

    class newth extends Thread{
    public void run(){
    for(int i=1;i<=100;i++)
    {
    try{
    Thread.sleep(50); 
    }
    catch(InterruptedException e){
    
    }
    if((i<1) && (i>15)){
    //Label2.setText("TAjmir");
    }
    else {
    ImageIcon obj=new ImageIcon("C:\\Users\\ftc\\Desktop\\image\\joker.png");
   // Label1.setIcon(obj);
    }
//    progress.setValue(i);
    if(i==100){
        
        scn.show();
        dispose();    
        }
      }}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 683));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/animated.gif"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 683));
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 683));
        getContentPane().add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_main.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().add(jLabel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash_scrren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash_scrren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash_scrren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash_scrren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash_scrren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
